import StyleDictionary from 'style-dictionary';

const sd = new StyleDictionary({
  source: ['tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [{
        destination: 'theme.gen.css', // 生成されるCSSファイル
        format: 'css/tailwind-v4'
      }]
    }
  }
});

// Tailwind v4 用のカスタムフォーマット
sd.registerFormat({
  name: 'css/tailwind-v4',
  format: function({ dictionary }) {
    const lines = [];
    lines.push('@theme {');

    dictionary.allTokens.forEach(token => {
      // 【修正】手動でのプレフィックス付与をやめ、token.name をそのまま使います。
      // token.name は既に 'color-night-900' のような形式になっています。
      const prop = `--${token.name}`;

      lines.push(`  ${prop}: ${token.value};`);
    });

    lines.push('}');
    return `/**
 * Generated by Style Dictionary
 * Do not edit directly
 */
${lines.join('\n')}
`;
  }
});

await sd.buildAllPlatforms();
