services:
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({_id:'rs0', members:[{_id:0, host:'localhost:27017'}]}).ok } catch(e) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 5s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data: {}
  redis-data: {}
